# Generated by Django 4.1.4 on 2022-12-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_days_completed', models.IntegerField(default=0)),
                ('progress', models.BooleanField(blank=True, null=True)),
                ('Report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.reports')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.usermodel')),
            ],
        ),
    ]
