# Generated by Django 4.1.4 on 2022-12-29 07:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docterpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.doctor')),
            ],
        ),
    ]
