# Generated by Django 4.1.4 on 2022-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
