# Generated by Django 4.1.4 on 2022-12-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_reports_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docterpatient',
            name='patients',
        ),
        migrations.AddField(
            model_name='docterpatient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.usermodel'),
        ),
    ]
